version: "3.3"
services:
  db:
    image: postgres
    container_name: postgres-container
    networks:
      - development-network
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nativa
    ports:
      - "5432:5432"

networks:
    development-network:
        driver: bridge      